apiVersion: v1
kind: ServiceAccount
metadata:
  name: goods-service-sa-prod
  namespace: morupark-prod
  annotations:
    iam.gke.io/gcp-service-account: goods-service-sa-prod@yourssu-morupark.iam.gserviceaccount.com
