server:
  port: 8081

spring:
  application:
    name: auth-service

management:
  endpoint:
    health:
      probes:
        enabled: true

  endpoints:
    web:
      exposure:
        include: health,info,metrics

security:
  jwt:
    secret: thisIsASecretKeyForJWTGenerationChangeMe
    access-token-expiration: 86400000 # 24 hours in milliseconds

logging:
  level:
    com.yourssu.morupark: DEBUG

---
spring:
  config:
    activate:
      on-profile: prod
  
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    datasource:
      hikari:
        initializationFailTimeout: 0
        connectionTimeout: 30000
        validationTimeout: 5000
        maximumPoolSize: 5
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    com.yourssu.morupark: INFO
