server:
  port: 8081

spring:
  application:
    name: auth-service

management:
  endpoint:
    health:
      probes:
        enabled: true

  endpoints:
    web:
      exposure:
        include: health,info,metrics

security:
  jwt:
    secret: ${JWT_SECRET:thisIsASecretKeyForJWTGenerationChangeMe}  
    access-token-expiration: 86400000 # 24 hours in milliseconds

app:
  server-url: ${APP_SERVER_URL:http://localhost:8000}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /auth-service/v3/api-docs

logging:
  level:
    com.yourssu.morupark: DEBUG

---
spring:
  config:
    activate:
      on-profile: prod
  
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    datasource:
      hikari:
        initializationFailTimeout: 0
        connectionTimeout: 30000
        validationTimeout: 5000
        maximumPoolSize: 5
  
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: OAUTHBEARER
      sasl.jaas.config: org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required;
      sasl.login.callback.handler.class: com.google.cloud.hosted.kafka.auth.GcpLoginCallbackHandler

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

security:
  jwt:
    secret: ${JWT_SECRET}

logging:
  level:
    com.yourssu.morupark: INFO
