apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: morupark-prod-ingress
  namespace: morupark-prod
  labels:
    app.kubernetes.io/name: morupark-prod-ingress
    app.kubernetes.io/part-of: morupark-msa
    environment: production
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "morupark-static-ip"
    networking.gke.io/managed-certificates: "morupark-managed-cert-prod"
spec:
  ingressClassName: "gce"
  rules:
  - host: api.morupark.urssu.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-gateway
            port:
              number: 80
