apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: morupark-dev
spec:
  serviceName: kafka
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      initContainers:
        - name: kafka-storage-format
          image: confluentinc/cp-kafka:7.4.0
          command:
            - sh
            - -c
            - |
              set -ex
              if [ -f /var/lib/kafka/data/meta.properties ]; then
                echo "Kafka storage already formatted. Skipping."
                exit 0
              fi

              CONFIG_FILE="/tmp/server.properties"
              echo "node.id=$KAFKA_NODE_ID" > "$CONFIG_FILE"
              echo "process.roles=controller" >> "$CONFIG_FILE"
              echo "controller.quorum.voters=$KAFKA_CONTROLLER_QUORUM_VOTERS" >> "$CONFIG_FILE"
              echo "listeners=CONTROLLER://:9093" >> "$CONFIG_FILE"
              echo "controller.listener.names=CONTROLLER" >> "$CONFIG_FILE"

              kafka-storage format \
                --config "$CONFIG_FILE" \
                --cluster-id "$CLUSTER_ID"
          env:
            - name: CLUSTER_ID
              value: "abcdefghijklmnopqrstuv"
            - name: KAFKA_LOG_DIRS
              value: "/var/lib/kafka/data"
            - name: KAFKA_NODE_ID
              value: "0"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "0@kafka-0.kafka.morupark-dev.svc.cluster.local:9093"
            - name: KAFKA_PROCESS_ROLES # Add this for initContainer
              value: "broker,controller"
          volumeMounts:
            - name: kafka-data
              mountPath: /var/lib/kafka/data
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.4.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_NODE_ID
              value: "0" # For single node setup, fixed to 0
            - name: KAFKA_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://:9092,CONTROLLER://:9093"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-0.kafka.morupark-dev.svc.cluster.local:9092"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "0@kafka-0.kafka.morupark-dev.svc.cluster.local:9093"
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_GROUP_INITIAL_REBALANCING_DELAY_MS
              value: "0"
            - name: CLUSTER_ID
              value: "abcdefghijklmnopqrstuv" # 임의의 고유 ID (22자)
            - name: KAFKA_LOG_DIRS
              value: "/var/lib/kafka/data"
            - name: KAFKA_HEAP_OPTS
              value: "-Xms256m -Xmx256m"
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"

          volumeMounts:
            - name: kafka-data
              mountPath: /var/lib/kafka/data

          readinessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 30
            periodSeconds: 10

          livenessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 60
            periodSeconds: 30

  volumeClaimTemplates:
    - metadata:
        name: kafka-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: morupark-dev
spec:
  ports:
    - port: 9092
      targetPort: 9092
  selector:
    app: kafka