apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: morupark-gcp-secrets
  namespace: morupark-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-store
    kind: SecretStore
  target:
    name: morupark-gcp-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: morupark-db-password
    - secretKey: JWT_SECRET
      remoteRef:
        key: morupark-jwt-secret
    - secretKey: DB_USERNAME
      remoteRef:
        key: morupark-db-username
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: morupark-redis-password