apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: morupark-gcp-secrets-provider
  namespace: morupark-dev
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/yourssu-morupark/secrets/morupark-jwt-secret/versions/latest"
        fileName: "JWT_SECRET"
      - resourceName: "projects/yourssu-morupark/secrets/morupark-db-username/versions/latest"
        fileName: "DB_USERNAME"
      - resourceName: "projects/yourssu-morupark/secrets/morupark-db-password/versions/latest"
        fileName: "DB_PASSWORD"
      - resourceName: "projects/yourssu-morupark/secrets/morupark-redis-password/versions/latest"
        fileName: "REDIS_PASSWORD"
  secretObjects:
    - secretName: morupark-gcp-secrets
      type: Opaque
      data:
        - key: JWT_SECRET
          objectName: "JWT_SECRET"
        - key: DB_USERNAME
          objectName: "DB_USERNAME"
        - key: DB_PASSWORD
          objectName: "DB_PASSWORD"
        - key: REDIS_PASSWORD
          objectName: "REDIS_PASSWORD"
