apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: morupark-dev
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: auth-service
        env:
          - name: SPRING_JPA_HIBERNATE_DDL_AUTO
            value: none
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:mysql://127.0.0.1:3306/moruparkdb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul"
        resources:
          requests:
            memory: "1Gi"
            cpu: "50m"
          limits:
            memory: "2Gi"
            cpu: "200m"
